config/routes.rb
WebTutor::Application.routes.draw do

  root :to => 'access#index'
    
  resources :tutorials do
    resources :comments
  end

  resources :users
  
 get "/404", :to => "errors#error_404"
  get 'home', :to => "access#index"
  get 'owner-home', :to => "access#index"
  
  get '/mathematics', :to => "tutorials#Math"
  get '/reading', :to => "tutorials#Reading"
  
get '/writing', :to => "tutorials#Writing"
  
  match ':controller(/:action(/:id))', :via => [:get,:post]
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #has_secure_password
  attr_accessible :body, :tutorial_id
  
  validates_presence_of :tutorial_id
  validates_presence_of :body
  belongs_to :tutorial
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 #before_filter :confirm_logged_in

 # GET /comments
  # GET /comments.json
  #def index
    #@comments = Comment.all

    #respond_to do |format|
   #   format.html # index.html.erb
  #    format.json { render json: @comments }
 #   end
 # end

  # GET /comments/1/edit
  #def edit
   # @comment = Comment.find(params[:id])
 # end

  # POST /comments
  # POST /comments.json
  def create
    @tutorial = Tutorial.find(params[:tutorial_id])
    @comment = @tutorial.comments.create(params[:comment])
@comment.comment_name = session['first_name']
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @tutorial }
        format.json { render json: @comment, status: :created, location: @comment }
        format.js #responding to javascript / create.js.erb will be called
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  #def update
   # @comment = Comment.find(params[:id])

    #respond_to do |format|
     # if @comment.update_attributes(params[:comment])
      #  format.html { redirect_to @comment }
       # format.json { head :no_content }
  #else
  # format.html { render action: "edit" }
#format.json { render json: @comment.errors, status: :unprocessable_entity }
#end
 #end
#end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to tutorial_path(@comment.tutorial_id) }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <p>
      <strong> <%= comment.comment_name %> posted <%= time_ago_in_words(comment.created_at) %> ago</strong> <br />
      <%= h(comment.body) %>
    <strong> <%= if session[:first_name] == comment.comment_name
link_to 'Delete', {:action=>"destroy", :controller=>"comments", :tutorial_id=> comment.tutorial_id, :id=> comment.id}, method: :delete, data: { confirm: 'Are you sure?' }
end %>
    </p>
    <% end %> </strong>



app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tutorial_id %><br />
    <%= f.number_field :tutorial_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment)) %>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Tutorial</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.body %></td>
    <td><%= comment.tutorial_id %></td>
    <td><%= link_to 'Show', {:action=>"show", :controller=>"comments", :tutorial_id=> comment.tutorial_id, :id=> comment.id} %></td>
    <td><%= link_to 'Edit', {:action=>"edit", :controller=>"comments", :tutorial_id=> comment.tutorial_id, :id=> comment.id} %></td>
    <td><%= link_to 'Destroy', method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Tutorial:</b>
  <%= @comment.tutorial_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>