config/routes.rb
WebTutor::Application.routes.draw do

  root :to => 'access#index'
    
  resources :tutorials do
    resources :comments
  end

  resources :users
  
 get "/404", :to => "errors#error_404"
  get 'home', :to => "access#index"
  get 'owner-home', :to => "access#index"
  
  get '/mathematics', :to => "tutorials#Math"
  get '/reading', :to => "tutorials#Reading"
  
get '/writing', :to => "tutorials#Writing"
  
  match ':controller(/:action(/:id))', :via => [:get,:post]
  
  

end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
#has_secure_password
def self.search(search)
  search_condition = "%" + search + "%"
  find(:all, :conditions => ['tutorial_name ILIKE ? OR tutorial_discription ILIKE ?', search_condition, search_condition])
end

  attr_accessible :tutorial_date_release, :tutorial_discription, :tutorial_name, :tutorial_path, :tutorial_teacher_name, :avatar, :CategoryID, :TutorialType
  
  belongs_to :category
  
  has_many :comments, dependent: :destroy #relationship between comments and tutorials (if u delete a tutorials all comments will be deleted)
  
  scope :math, lambda{where(:CategoryID => 'Mathematics')}
  scope :reading, lambda{where(:CategoryID => 'Reading')}
  scope :writing, lambda{where(:CategoryID => 'Writing')}
  
  validates_presence_of :tutorial_date_release
  validates_presence_of :tutorial_discription
  validates_presence_of :tutorial_name
  #validates_presence_of :tutorial_teacher_name
  ###Paperclip
#has_attached_file :avatar,:storage => :s3,
#:s3_credentials => "#{Rails.root}/config/s3.yml",:path => ":attachment/:id.:extension",:bucket => 'webtutor'
has_attached_file :avatar,:storage => :s3,
:s3_credentials => "#{Rails.root}/config/s3.yml",
:path => ":attachment/:id.:extension", 
:url => ":s3_domain_url"
#has_attached_file :avatar
 validates_attachment_content_type :avatar, :content_type => /.*/
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  # GET /tutorials
  # GET /tutorials.json

before_filter :confirm_logged_in, :except => [:create]
  def index
    @tutorials = Tutorial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tutorials }
    end
  end
  def search
    @tutorials = Tutorial.search params[:search]
  end


  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
    @tutorial = Tutorial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tutorial }
    end
  end

  # GET /tutorials/new
  # GET /tutorials/new.json
  def new
    if session[:user_role] == 'student'
        redirect_to('/404')
    else    
      @tutorial = Tutorial.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @tutorial }
      end
    end
  end

  # GET /tutorials/1/edit
  def edit
    if session[:user_role] == 'student'
        redirect_to('/404')
    else    
      @tutorial = Tutorial.find(params[:id])
    end
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    if session[:user_role] == 'student'
        redirect_to('/404')
    else    
      @tutorial = Tutorial.new(params[:tutorial])

      respond_to do |format|
          if @tutorial.save
            format.html { redirect_to @tutorial, notice: 'Tutorial was successfully created.' }
            format.json { render json: @tutorial, status: :created, location: @tutorial }
          else
            format.html { render action: "new" }
            format.json { render json: @tutorial.errors, status: :unprocessable_entity }
          end
        end
    end
  end

  # PUT /tutorials/1
  # PUT /tutorials/1.json
  def update
    if session[:user_role] == 'student'
        redirect_to('/404')
    else    
      @tutorial = Tutorial.find(params[:id])

      respond_to do |format|
          if @tutorial.update_attributes(params[:tutorial])
            format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: "edit" }
            format.json { render json: @tutorial.errors, status: :unprocessable_entity }
          end
        end
      end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    if session[:user_role] == 'student'
        redirect_to('/404')
    else    
      @tutorial = Tutorial.find(params[:id])
      @tutorial.destroy

      respond_to do |format|
        format.html { redirect_to tutorials_url }
        format.json { head :no_content }
      end
    end
  end
  
  def Math
  @tut1 = Tutorial.math
  end
  def Reading
  @tut2 = Tutorial.reading
  end
  def Writing
  @tut3 = Tutorial.writing
  end
  
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/Math.html.erb
<header>
<%= render 'access/navigation' %>
</header>
<br/>
<div>
<h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mathematics Tutorials</h1>

<br />
</div>
<br/>
<br/>
<table id="tutorials">
  <tr class="tutorials_tr">
    <th class="tutorials_th">Tutorial Name</th>
    <th class="tutorials_th">Tutorial Type</th>
    <th class="tutorials_th">Date Released</th>
    <th class="tutorials_th">Category</th>
	<th class="tutorials_th">Functions</th>
  </tr>

<% @tut1.each do |tutorial| %>
  <tr class="tutorials_tr">
    <td class="tutorials_td"><%= tutorial.tutorial_name %></td>
    <td class="tutorials_td"><%= tutorial.TutorialType %></td>
    <td class="tutorials_td"><%= tutorial.tutorial_date_release %></td>
    <td class="tutorials_td"><%= tutorial.CategoryID %></td>
	
    
    <td class="tutorials_td"><%= link_to 'Show', tutorial %>  <%= if session[:user_role] == 'owner' 
    		link_to 'Edit', edit_tutorial_path(tutorial)
    		end %>
    	<%= if session[:user_role] == 'owner'
    		link_to 'Delete', tutorial, method: :delete, data: { confirm: 'Are you sure?' } 
    		end%>
  </tr>
<% end %>
</table>

app/views/tutorials/Reading.html.erb
<header>
<%= render 'access/navigation' %>
</header>
<br/>
<div>
<h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Reading Tutorials</h1>

<br />
</div>
<br/>
<br/>
<table id="tutorials">
  <tr class="tutorials_tr">
    <th class="tutorials_th">Tutorial Name</th>
    <th class="tutorials_th">Tutorial Type</th>
    <th class="tutorials_th">Date Released</th>
    <th class="tutorials_th">Category</th>
	<th class="tutorials_th">Functions</th>
  </tr>

<% @tut2.each do |tutorial| %>
  <tr class="tutorials_tr">
    <td class="tutorials_td"><%= tutorial.tutorial_name %></td>
    <td class="tutorials_td"><%= tutorial.TutorialType %></td>
    <td class="tutorials_td"><%= tutorial.tutorial_date_release %></td>
    <td class="tutorials_td"><%= tutorial.CategoryID %></td>
	
    
    <td class="tutorials_td"><%= link_to 'Show', tutorial %>  <%= link_to 'Edit', edit_tutorial_path(tutorial) %>  <%= link_to 'Delete', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/tutorials/Writing.html.erb
<header>
<%= render 'access/navigation' %>
</header>
<br/>
<div>
<h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Writing Tutorials</h1>

<br />
</div>
<br/>
<br/>
<table id="tutorials">
  <tr class="tutorials_tr">
    <th class="tutorials_th">Tutorial Name</th>
    <th class="tutorials_th">Tutorial Type</th>
    <th class="tutorials_th">Date Released</th>
    <th class="tutorials_th">Category</th>
	<th class="tutorials_th">Functions</th>
  </tr>

<% @tut3.each do |tutorial| %>
  <tr class="tutorials_tr">
    <td class="tutorials_td"><%= tutorial.tutorial_name %></td>
    <td class="tutorials_td"><%= tutorial.TutorialType %></td>
    <td class="tutorials_td"><%= tutorial.tutorial_date_release %></td>
    <td class="tutorials_td"><%= tutorial.CategoryID %></td>
	
    
    <td class="tutorials_td"><%= link_to 'Show', tutorial %> <%= if session[:user_role] == 'owner' 
    		link_to 'Edit', edit_tutorial_path(tutorial)
    		end %>
    	<%= if session[:user_role] == 'owner'
    		link_to 'Delete', tutorial, method: :delete, data: { confirm: 'Are you sure?' } 
    		end%>
  </tr>
<% end %>
</table>

app/views/tutorials/_form.html.erb
<%= form_for(@tutorial) do |f| %>
  <% if @tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% @tutorial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" align="left">
    &nbsp;&nbsp;&nbsp;<b><%= f.label :tutorial_name %></b>
    &nbsp;&nbsp;&nbsp;<%= f.text_field :tutorial_name %>
  </div>
  
  <div class="field" align="left">
  	&nbsp;&nbsp;&nbsp;<b><%= f.label :Tutoroal_Type %></b>
	&nbsp;&nbsp;&nbsp;<select name="tutorial[TutorialType]">
		  	<option value="Audio">Audio</option>
		  	<option value="Video">Video</option>
		  	<option value="Document">Documents</option>
		  </select>
	  	</div>
  <div class="field" align="left">
    &nbsp;&nbsp;&nbsp;<b><%= f.label :Date_of_release %></b>
    <%= f.date_select :tutorial_date_release %>
  </div>
  <!--<div class="field">
    <%= f.label :tutorial_teacher_name %><br />
    <%= f.text_area :tutorial_teacher_name %>
  </div>-->
  <div class="field" align="left">
    &nbsp;&nbsp;&nbsp;<b><%= f.label :Description%></b>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.text_area :tutorial_discription,:cols => "40", :rows => "5" %>
  </div>
  <!--<div class="field">
    <%= f.label :tutorial_path %><br />
    <%= f.text_field :tutorial_path %>
  </div>-->
  
  <div class="field" align="left">
  	&nbsp;&nbsp;&nbsp;<b><%= f.label :CategoryID %></b>
		 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<select name="tutorial[CategoryID]">
		  	<option value="Mathematics">Mathematics</option>
		  	<option value="Reading">Reading</option>
		  	<option value="Writing">Writing</option>
		  </select>
	  	</div>
	  	<div class="field" align="left">
	   &nbsp;&nbsp;&nbsp;<b><%= f.label :Select_file %></b>
	   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.file_field :avatar %>
	  </div>
  <div class="actions" align="left">
    &nbsp;&nbsp;&nbsp;<b><%= f.submit %></b>
  </div>
<% end %>

app/views/tutorials/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', :controller => 'tutorial', :action => 'index'  %></li>
  <%= render 'tutorial/navigation_links' %>
</ul>

app/views/tutorials/_navigation_links.html.erb

<li><%= link_to 'Tutorials', :controller => 'tutorials'  %></li>
<li><%= link_to("My Profile", :controller => 'users', :action => 'show', :id => session[:user_id]) %></li> |
<li><%= link_to 'Logout', :controller => 'access', :action => 'logout'  %></li>|
<li>
<div id="search">
<%= form_tag :controller => 'tutorials', :action => 'search', :method => 'get' do %>
      <%= text_field_tag :search, params[:search], :id => 'search_field' %>
      <%= submit_tag "Search", :name => nil %> 
 <% end %> 
</div>
</li>

app/views/tutorials/edit.html.erb
<header>
<%= render 'access/navigation' %>
</header>
<br/>
<h1>Editing tutorial</h1>
<br/>
<%= render 'form' %>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<header>
<%= render 'access/navigation' %>
</header>
<br/>
<div>
<h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tutorials</h1>

<br />
</div>
<br/>
<br/>
<table id="tutorials">
  <tr class="tutorials_tr">
    <th class="tutorials_th">Tutorial Name</th>
    <th class="tutorials_th">Tutorial Type</th>
    <th class="tutorials_th">Date Released</th>
    <th class="tutorials_th">Category</th>
	<th class="tutorials_th">Functions</th>
  </tr>

<% @tutorials.each do |tutorial| %>
  <tr class="tutorials_tr">
    <td class="tutorials_td"><%= tutorial.tutorial_name %></td>
    <td class="tutorials_td"><%= tutorial.TutorialType %></td>
    <td class="tutorials_td"><%= tutorial.tutorial_date_release %></td>
    <td class="tutorials_td"><%= tutorial.CategoryID %></td>
	
    
    <td class="tutorials_td">
    	<%= if session[:user_role] == 'owner' 
    		link_to 'Edit', edit_tutorial_path(tutorial)
    		end %>
    	<%= if session[:user_role] == 'owner'
    		link_to 'Delete', tutorial, method: :delete, data: { confirm: 'Are you sure?' } 
    		end%>
		<%= link_to 'Show', tutorial %>
    </td>
  </tr>
<% end %>
</table>

app/views/tutorials/new.html.erb
<header>
<%= render 'access/navigation' %>
</header>
<br/>
<h1>New tutorial</h1>
<br/>
<%= render 'form' %>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/search.html.erb

<% @page_title = "User Menu" %>
<header>
<%= render 'access/navigation' %>
</header>
<br/>
<% if (@tutorials.length == 0)%>
<hl>No Results Founds</h1>
<% end %>
<br/>
<% if (@tutorials.length > 0)%>
<hl>Results</h1>
<% end %>
<br/>


<br />
<table id="tutorials">
  <tr class="tutorials_tr">
    <th class="tutorials_th">Tutorial Name</th>
    <th class="tutorials_th">Tutorial Type</th>
    <th class="tutorials_th">Date Released</th>
    <th class="tutorials_th">Category</th>
	<th class="tutorials_th">Functions</th>
  </tr>

<% @tutorials.each do |tutorial| %>
  <tr class="tutorials_tr">
    <td class="tutorials_td"><%= tutorial.tutorial_name %></td>
    <td class="tutorials_td"><%= tutorial.TutorialType %></td>
    <td class="tutorials_td"><%= tutorial.tutorial_date_release %></td>
    <td class="tutorials_td"><%= tutorial.CategoryID %></td>
	
    
    <td class="tutorials_td">
    	<%= if session[:user_role] == 'owner' 
    		link_to 'Edit', edit_tutorial_path(tutorial)
    		end %>
    	<%= if session[:user_role] == 'owner'
    		link_to 'Delete', tutorial, method: :delete, data: { confirm: 'Are you sure?' } 
    		end%>
		<%= link_to 'Show', tutorial %>
    </td>
  </tr>
<% end %>
</table>

app/views/tutorials/show.html.erb
<% @page_title = "Tutorial Page" %>
<header>
<%= render 'access/navigation' %>
</header>
<br/>
<br />
 <p> <b><center><font size="5"><%= @tutorial.tutorial_name  %></font></center></b></p>
<p><center><iframe 
      src="<%= @tutorial.avatar %>" style="width:800px; height:600px;" frameborder="5"/></iframe>

</center> </p>
<textarea readonly rows="4" cols="100">
<%= @tutorial.tutorial_discription  %>
</textarea> 


<br />
<%= link_to 'Back', tutorials_path %>
<br />
<h2> Comments </h2>
<div id="comments">
  <%= render :partial => @tutorial.comments.reverse %>
</div>

<%= form_for([@tutorial, Comment.new], remote: true) do |f| %>
   <p>
     <%= f.label :body, "New Comment" %><br />
	 <%= f.text_area :body,:cols => "40", :rows => "1" %>
   </p>
   <p><%= f.submit "Add Comment" %></p>
<% end %>